version: "3"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    environment:
      - TZ=Europe/Madrid    
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
